FILEPATH = C:/Users/ejwei/Desktop/Personsal/School/Semester_5/3150/project/schoolProjects/3150_vi_project/ECEditorTest/ECEditorTest/
FILES = $(FILEPATH)ECEditorTest.cpp $(FILEPATH)ECTextViewImp.h $(FILEPATH)ECTextViewImp.cpp $(FILEPATH)ECObserver.h $(FILEPATH)ECCommand.h $(FILEPATH)ECCommand.cpp $(FILEPATH)ECTextEditor.h

CC = g++

CFLAGS = -std=c++14 -Wall -I.

makeall: $(FILES)
	$(CC) -o makeall $(FILES) $(CFLAGS)
