FILEPATH = ECProject/
FILES = $(FILEPATH)ECEditorTest.cpp $(FILEPATH)ECTextViewImp.h $(FILEPATH)ECTextViewImp.cpp $(FILEPATH)ECObserver.h $(FILEPATH)ECCommand.h $(FILEPATH)ECCommand.cpp $(FILEPATH)ECTextEditor.h

CC = g++

CFLAGS = -std=c++14 -Wall -I.

makeall: $(FILES)
	$(CC) -o project $(FILES) $(CFLAGS)
